version: "2.4"
services:
  web:
    build: .
    ports:
     - "80:5000"
    depends_on:
     - "redis"
    volumes:
     - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
    volumes:
      - type: volume
        source: data
        target: /data
volumes:
  data:               